<?php require_once 'header.php' ?>
    <section class="page-bg">
        <div class="container jobs">
            <div class="page-bg-text">
                <h1>
                    消费者协议
                    <p>
                    </p>
                </h1>
            </div>
        </div>
    </section>
    <section class="page-content">
        <div class="container">
            <div class="row">
                <div class="col-md-3 col-sm-3 col-xs-3 left">
                    <?php require_once 'page_nav.php' ?>
                </div>
                <div class="col-md-9 col-sm-9 col-xs-9 right">
                    <div class="main-content">
                        <h3>
                            消费者协议
                        </h3>
                      <p style="box-sizing:border-box;margin-top:0px;margin-bottom:0px;padding:0px;color:#333333;font-family:&quot;font-size:14px;white-space:normal;widows:1;line-height:22px;background-color:#FFFFFF;">
	<span style="box-sizing:border-box;margin:0px;padding:0px;font-family:Arial;color:#666666;letter-spacing:0px;font-weight:bold;font-size:12px;">本协议是由您</span><span style="box-sizing:border-box;margin:0px;padding:0px;font-family:宋体;color:#666666;letter-spacing:0px;font-weight:bold;font-size:12px;">（柒付云计费个人注册会员或使用柒付消费的消费者）</span><span style="box-sizing:border-box;margin:0px;padding:0px;font-family:Arial;color:#666666;letter-spacing:0px;font-weight:bold;font-size:12px;">与</span><span style="box-sizing:border-box;margin:0px;padding:0px;font-family:宋体;color:#666666;letter-spacing:0px;font-weight:bold;font-size:12px;">黄山俊网电子商务</span><span style="box-sizing:border-box;margin:0px;padding:0px;font-family:Arial;color:#666666;letter-spacing:0px;font-weight:bold;font-size:12px;">有限公司之间就</span><span style="box-sizing:border-box;margin:0px;padding:0px;font-family:宋体;color:#666666;letter-spacing:0px;font-weight:bold;font-size:12px;">行柒付平台</span><span style="box-sizing:border-box;margin:0px;padding:0px;font-family:Arial;color:#666666;letter-spacing:0px;font-weight:bold;font-size:12px;">服务等相关事宜所订立的契约，本协议具有合同效力。</span>
</p>
<p style="box-sizing:border-box;margin-top:0px;margin-bottom:0px;padding:0px;color:#333333;font-family:&quot;font-size:14px;line-height:20px;white-space:normal;widows:1;background-color:#FFFFFF;">
	<br />
</p>
<p style="box-sizing:border-box;margin-top:0px;margin-bottom:0px;padding:0px;color:#333333;font-family:&quot;font-size:14px;white-space:normal;widows:1;line-height:22px;background-color:#FFFFFF;">
	<span style="box-sizing:border-box;margin:0px;padding:0px;color:#666666;letter-spacing:0px;font-size:12px;"><span style="box-sizing:border-box;margin:0px;padding:0px;font-family:Arial;"> 本协议中“</span><span style="box-sizing:border-box;margin:0px;padding:0px;font-family:宋体;">柒付云计费</span></span><span style="box-sizing:border-box;margin:0px;padding:0px;font-family:Arial;color:#666666;letter-spacing:0px;font-size:12px;">”(<span style="box-sizing:border-box;margin:0px;padding:0px;font-family:宋体;">以下简称</span></span><span style="box-sizing:border-box;margin:0px;padding:0px;font-family:宋体;color:#666666;letter-spacing:0px;font-size:12px;">柒付</span><span style="box-sizing:border-box;margin:0px;padding:0px;font-family:Arial;color:#666666;letter-spacing:0px;font-size:12px;">)<span style="box-sizing:border-box;margin:0px;padding:0px;font-family:宋体;">指由</span></span><span style="box-sizing:border-box;margin:0px;padding:0px;font-family:宋体;color:#666666;letter-spacing:0px;font-size:12px;">深圳奇咖网络科技有限公司运营的网络交易平台，域名为</span><span style="box-sizing:border-box;margin:0px;padding:0px;color:#666666;letter-spacing:0px;font-size:12px;font-family:宋体;">www.7foo.com</span><span style="box-sizing:border-box;margin:0px;padding:0px;font-family:Arial;color:#666666;letter-spacing:0px;font-size:12px;">。请您仔细阅读本协议，您点击“</span><span style="box-sizing:border-box;margin:0px;padding:0px;font-family:宋体;color:#666666;letter-spacing:0px;font-size:12px;">同意消费者协议</span><span style="box-sizing:border-box;margin:0px;padding:0px;font-family:Arial;color:#666666;letter-spacing:0px;font-size:12px;">”<span style="box-sizing:border-box;margin:0px;padding:0px;font-family:宋体;">按钮后，本协议即构成对双方有约束力的法律文件。</span></span>
</p>
<p style="box-sizing:border-box;margin-top:0px;margin-bottom:0px;padding:0px;color:#333333;font-family:&quot;font-size:14px;white-space:normal;widows:1;line-height:22px;background-color:#FFFFFF;">
	<span style="box-sizing:border-box;margin:0px;padding:0px;font-family:Arial;color:#666666;letter-spacing:0px;font-weight:bold;font-size:12px;">一、&nbsp;协议内容及签署</span>
</p>
<p style="box-sizing:border-box;margin-top:0px;margin-bottom:0px;padding:0px;color:#333333;font-family:&quot;font-size:14px;white-space:normal;widows:1;line-height:22px;background-color:#FFFFFF;">
	<span style="box-sizing:border-box;margin:0px;padding:0px;font-family:Arial;color:#666666;letter-spacing:0px;font-size:12px;"> 1<span style="box-sizing:border-box;margin:0px;padding:0px;font-family:宋体;">、本协议内容包括协议正文及所有</span></span><span style="box-sizing:border-box;margin:0px;padding:0px;font-family:宋体;color:#666666;letter-spacing:0px;font-size:12px;">柒付</span><span style="box-sizing:border-box;margin:0px;padding:0px;font-family:Arial;color:#666666;letter-spacing:0px;font-size:12px;">已经发布的或将来可能发布的各类规则。所有规则为本协议不可分割的组成部分，与协议正文具有同等法律效力。除另行明确声明外，任何</span><span style="box-sizing:border-box;margin:0px;padding:0px;font-family:宋体;color:#666666;letter-spacing:0px;font-size:12px;">柒付</span><span style="box-sizing:border-box;margin:0px;padding:0px;font-family:Arial;color:#666666;letter-spacing:0px;font-size:12px;">提供的服务均受本协议约束。</span>
</p>
<p style="box-sizing:border-box;margin-top:0px;margin-bottom:0px;padding:0px;color:#333333;font-family:&quot;font-size:14px;white-space:normal;widows:1;line-height:22px;background-color:#FFFFFF;">
	<span style="box-sizing:border-box;margin:0px;padding:0px;font-family:Arial;color:#666666;letter-spacing:0px;font-size:12px;"> 2<span style="box-sizing:border-box;margin:0px;padding:0px;font-family:宋体;">、</span></span><span style="box-sizing:border-box;margin:0px;padding:0px;font-family:Arial;color:#666666;letter-spacing:0px;font-weight:bold;font-size:12px;">您应当在使用</span><span style="box-sizing:border-box;margin:0px;padding:0px;font-family:宋体;color:#666666;letter-spacing:0px;font-weight:bold;font-size:12px;">柒付</span><span style="box-sizing:border-box;margin:0px;padding:0px;font-family:Arial;color:#666666;letter-spacing:0px;font-weight:bold;font-size:12px;">之前认真阅读全部协议内容，对于协议中以粗体标注的内容，您应重点阅读。</span><span style="box-sizing:border-box;margin:0px;padding:0px;font-family:Arial;color:#666666;letter-spacing:0px;font-size:12px;">如您对协议有任何疑问，应向</span><span style="box-sizing:border-box;margin:0px;padding:0px;font-family:宋体;color:#666666;letter-spacing:0px;font-size:12px;">柒付</span><span style="box-sizing:border-box;margin:0px;padding:0px;font-family:Arial;color:#666666;letter-spacing:0px;font-size:12px;">咨询。但无论您事实上是否在使用</span><span style="box-sizing:border-box;margin:0px;padding:0px;font-family:宋体;color:#666666;letter-spacing:0px;font-size:12px;">柒付</span><span style="box-sizing:border-box;margin:0px;padding:0px;font-family:Arial;color:#666666;letter-spacing:0px;font-size:12px;">之前认真阅读了本协议内容，只要您使用</span><span style="box-sizing:border-box;margin:0px;padding:0px;letter-spacing:0px;color:#666666;font-family:宋体;font-size:12px;">柒付</span><span style="box-sizing:border-box;margin:0px;padding:0px;font-family:Arial;color:#666666;letter-spacing:0px;font-size:12px;">，则本协议即对您产生约束，届时您不应以未阅读本协议的内容或者未获得</span><span style="box-sizing:border-box;margin:0px;padding:0px;font-family:宋体;color:#666666;letter-spacing:0px;font-size:12px;">柒付</span><span style="box-sizing:border-box;margin:0px;padding:0px;font-family:Arial;color:#666666;letter-spacing:0px;font-size:12px;">对您问询的解答等理由，主张本协议无效，或要求撤销本协议。</span>
</p>
<p style="box-sizing:border-box;margin-top:0px;margin-bottom:0px;padding:0px;color:#333333;font-family:&quot;font-size:14px;white-space:normal;widows:1;line-height:22px;background-color:#FFFFFF;">
	<span style="box-sizing:border-box;margin:0px;padding:0px;font-family:Arial;color:#666666;letter-spacing:0px;font-size:12px;"> 3<span style="box-sizing:border-box;margin:0px;padding:0px;font-family:宋体;">、您承诺接受并遵守本协议的约定。如果您不同意本协议的约定，您应立即停止</span></span><span style="box-sizing:border-box;margin:0px;padding:0px;font-family:宋体;color:#666666;letter-spacing:0px;font-size:12px;">消费</span><span style="box-sizing:border-box;margin:0px;padding:0px;font-family:Arial;color:#666666;letter-spacing:0px;font-size:12px;">程序或停止使用</span><span style="box-sizing:border-box;margin:0px;padding:0px;letter-spacing:0px;color:#666666;font-family:宋体;font-size:12px;">柒付</span><span style="box-sizing:border-box;margin:0px;padding:0px;font-family:Arial;color:#666666;letter-spacing:0px;font-size:12px;">。</span>
</p>
<p style="box-sizing:border-box;margin-top:0px;margin-bottom:0px;padding:0px;color:#333333;font-family:&quot;font-size:14px;white-space:normal;widows:1;line-height:22px;background-color:#FFFFFF;">
	<span style="box-sizing:border-box;margin:0px;padding:0px;font-family:Arial;color:#666666;letter-spacing:0px;font-size:12px;"> 4<span style="box-sizing:border-box;margin:0px;padding:0px;font-family:宋体;">、</span></span><span style="box-sizing:border-box;margin:0px;padding:0px;letter-spacing:0px;color:#666666;font-family:宋体;font-size:12px;">柒付</span><span style="box-sizing:border-box;margin:0px;padding:0px;font-family:Arial;color:#666666;letter-spacing:0px;font-size:12px;">有权根据需要不时地制订、修改本协议及/<span style="box-sizing:border-box;margin:0px;padding:0px;font-family:宋体;">或各类规则，并以网站公示的方式进行公告，不再单独通知您。变更后的协议和规则一经在网站公布后，立即自动生效。如您不同意相关变更，应当立即停止使用</span></span><span style="box-sizing:border-box;margin:0px;padding:0px;letter-spacing:0px;color:#666666;font-family:宋体;font-size:12px;">柒付</span><span style="box-sizing:border-box;margin:0px;padding:0px;font-family:Arial;color:#666666;letter-spacing:0px;font-size:12px;">。您继续使用</span><span style="box-sizing:border-box;margin:0px;padding:0px;letter-spacing:0px;color:#666666;font-family:宋体;font-size:12px;">柒付</span><span style="box-sizing:border-box;margin:0px;padding:0px;font-family:Arial;color:#666666;letter-spacing:0px;font-size:12px;">的，即表示您接受经修订的协议和规则。</span>
</p>
<p style="box-sizing:border-box;margin-top:0px;margin-bottom:0px;padding:0px;color:#333333;font-family:&quot;font-size:14px;white-space:normal;widows:1;line-height:22px;background-color:#FFFFFF;">
	<span style="box-sizing:border-box;margin:0px;padding:0px;font-family:Arial;color:#666666;letter-spacing:0px;font-weight:bold;font-size:12px;">二、&nbsp;</span><span style="box-sizing:border-box;margin:0px;padding:0px;font-family:宋体;color:#666666;letter-spacing:0px;font-weight:bold;font-size:12px;">消费</span>
</p>
<p style="box-sizing:border-box;margin-top:0px;margin-bottom:0px;padding:0px;color:#333333;font-family:&quot;font-size:14px;white-space:normal;widows:1;line-height:22px;background-color:#FFFFFF;">
	<span style="box-sizing:border-box;margin:0px;padding:0px;font-family:Arial;color:#666666;letter-spacing:0px;font-size:12px;"> 1<span style="box-sizing:border-box;margin:0px;padding:0px;font-family:宋体;">、</span></span><span style="box-sizing:border-box;margin:0px;padding:0px;font-family:宋体;color:#666666;letter-spacing:0px;font-size:12px;">消费</span><span style="box-sizing:border-box;margin:0px;padding:0px;font-family:Arial;color:#666666;letter-spacing:0px;font-size:12px;">者资格</span>
</p>
<p style="box-sizing:border-box;margin-top:0px;margin-bottom:0px;padding:0px;color:#333333;font-family:&quot;font-size:14px;white-space:normal;widows:1;line-height:22px;background-color:#FFFFFF;">
	<span style="box-sizing:border-box;margin:0px;padding:0px;font-family:Arial;color:#666666;letter-spacing:0px;font-size:12px;"> 您确认，在您完成注册程序或以其它</span><span style="box-sizing:border-box;margin:0px;padding:0px;letter-spacing:0px;color:#666666;font-family:宋体;font-size:12px;">柒付</span><span style="box-sizing:border-box;margin:0px;padding:0px;font-family:Arial;color:#666666;letter-spacing:0px;font-size:12px;">允许的方式</span><span style="box-sizing:border-box;margin:0px;padding:0px;font-family:宋体;color:#666666;letter-spacing:0px;font-size:12px;">（如：直接下单消费）</span><span style="box-sizing:border-box;margin:0px;padding:0px;font-family:Arial;color:#666666;letter-spacing:0px;font-size:12px;">实际使用</span><span style="box-sizing:border-box;margin:0px;padding:0px;letter-spacing:0px;color:#666666;font-family:宋体;font-size:12px;">柒付</span><span style="box-sizing:border-box;margin:0px;padding:0px;font-family:Arial;color:#666666;letter-spacing:0px;font-size:12px;">时，您应当是具备完全民事权利能力和完全民事行为能力的自然人。若您不具备前述主体资格，则您及您的监护人应承担因此而导致的一切后果，</span><span style="box-sizing:border-box;margin:0px;padding:0px;font-family:宋体;color:#666666;letter-spacing:0px;font-size:12px;">由您的</span><span style="box-sizing:border-box;margin:0px;padding:0px;font-family:Arial;color:#666666;letter-spacing:0px;font-size:12px;">监护人</span><span style="box-sizing:border-box;margin:0px;padding:0px;font-family:宋体;color:#666666;letter-spacing:0px;font-size:12px;">承担</span><span style="box-sizing:border-box;margin:0px;padding:0px;font-family:Arial;color:#666666;letter-spacing:0px;font-size:12px;">。</span>
</p>
<p style="box-sizing:border-box;margin-top:0px;margin-bottom:0px;padding:0px;color:#333333;font-family:&quot;font-size:14px;white-space:normal;widows:1;line-height:22px;background-color:#FFFFFF;">
	<span style="box-sizing:border-box;margin:0px;padding:0px;font-family:Arial;color:#666666;letter-spacing:0px;font-size:12px;"> 2<span style="box-sizing:border-box;margin:0px;padding:0px;font-family:宋体;">、</span></span><span style="box-sizing:border-box;margin:0px;padding:0px;font-family:宋体;color:#666666;letter-spacing:0px;font-size:12px;">订单</span>
</p>
<p style="box-sizing:border-box;margin-top:0px;margin-bottom:0px;padding:0px;color:#333333;font-family:&quot;font-size:14px;white-space:normal;widows:1;line-height:22px;background-color:#FFFFFF;">
	<span style="box-sizing:border-box;margin:0px;padding:0px;font-family:Arial;color:#666666;letter-spacing:0px;font-size:12px;"> 在您签署本协议，完成会员注册程序或以其它</span><span style="box-sizing:border-box;margin:0px;padding:0px;letter-spacing:0px;color:#666666;font-family:宋体;font-size:12px;">柒付</span><span style="box-sizing:border-box;margin:0px;padding:0px;font-family:Arial;color:#666666;letter-spacing:0px;font-size:12px;">允许的方式</span><span style="box-sizing:border-box;margin:0px;padding:0px;font-family:宋体;color:#666666;letter-spacing:0px;font-size:12px;">（如：直接下单消费）</span><span style="box-sizing:border-box;margin:0px;padding:0px;font-family:Arial;color:#666666;letter-spacing:0px;font-size:12px;">实际使用</span><span style="box-sizing:border-box;margin:0px;padding:0px;letter-spacing:0px;color:#666666;font-family:宋体;font-size:12px;">柒付</span><span style="box-sizing:border-box;margin:0px;padding:0px;font-family:Arial;color:#666666;letter-spacing:0px;font-size:12px;">时，</span><span style="box-sizing:border-box;margin:0px;padding:0px;font-family:宋体;color:#666666;letter-spacing:0px;font-size:12px;">柒付</span><span style="box-sizing:border-box;margin:0px;padding:0px;font-family:Arial;color:#666666;letter-spacing:0px;font-size:12px;">会向您提供唯一编号的</span><span style="box-sizing:border-box;margin:0px;padding:0px;font-family:宋体;color:#666666;letter-spacing:0px;font-size:12px;">柒付交易订单号码</span><span style="box-sizing:border-box;margin:0px;padding:0px;font-family:Arial;color:#666666;letter-spacing:0px;font-size:12px;">。您可以对</span><span style="box-sizing:border-box;margin:0px;padding:0px;font-family:宋体;color:#666666;letter-spacing:0px;font-size:12px;">你的订单进行查询</span><span style="box-sizing:border-box;margin:0px;padding:0px;font-family:Arial;color:#666666;letter-spacing:0px;font-size:12px;">。</span>
</p>
<p style="box-sizing:border-box;margin-top:0px;margin-bottom:0px;padding:0px;color:#333333;font-family:&quot;font-size:14px;white-space:normal;widows:1;line-height:22px;background-color:#FFFFFF;">
	<span style="box-sizing:border-box;margin:0px;padding:0px;font-family:宋体;color:#666666;letter-spacing:0px;font-weight:bold;font-size:12px;">你在交易过程中应当仔细核对交易金额是否与柒付商户对应网站中交易金额相同，以免发生纠纷</span><span style="box-sizing:border-box;margin:0px;padding:0px;font-family:Arial;color:#666666;letter-spacing:0px;font-weight:bold;font-size:12px;">。</span><span style="box-sizing:border-box;margin:0px;padding:0px;font-family:宋体;color:#666666;letter-spacing:0px;font-weight:bold;font-size:12px;">如因不仔细而错支付、多支付、少支付&nbsp;应及时与柒付取得联系。</span>
</p>
<p style="box-sizing:border-box;margin-top:0px;margin-bottom:0px;padding:0px;color:#333333;font-family:&quot;font-size:14px;white-space:normal;widows:1;line-height:22px;background-color:#FFFFFF;">
	<span style="box-sizing:border-box;margin:0px;padding:0px;font-family:Arial;color:#666666;letter-spacing:0px;font-size:12px;"> 3<span style="box-sizing:border-box;margin:0px;padding:0px;font-family:宋体;">、</span></span><span style="box-sizing:border-box;margin:0px;padding:0px;font-family:宋体;color:#666666;letter-spacing:0px;font-size:12px;">交易两天有保障</span>
</p>
<p style="box-sizing:border-box;margin-top:0px;margin-bottom:0px;padding:0px;color:#333333;font-family:&quot;font-size:14px;white-space:normal;widows:1;line-height:22px;background-color:#FFFFFF;">
	<span style="box-sizing:border-box;margin:0px;padding:0px;font-family:宋体;color:#666666;letter-spacing:0px;font-weight:bold;">若交易过程中发生纠纷，消费者需联系商户协商。若协商未果，请于交易当天联系柒付介入，我司将为您所支付的款项提供两天的担保，如超过两天未要求柒付介入将视为无纠纷交易，柒付不再为您的这必交易提供担保。</span>
</p>
<p style="box-sizing:border-box;margin-top:0px;margin-bottom:0px;padding:0px;color:#333333;font-family:&quot;font-size:14px;white-space:normal;widows:1;line-height:22px;background-color:#FFFFFF;">
	<span style="box-sizing:border-box;margin:0px;padding:0px;font-family:Arial;color:#666666;letter-spacing:0px;font-weight:bold;font-size:12px;"> 三、&nbsp;<span style="box-sizing:border-box;margin:0px;padding:0px;font-family:宋体;">柒付</span>服务</span>
</p>
<p style="box-sizing:border-box;margin-top:0px;margin-bottom:0px;padding:0px;color:#333333;font-family:&quot;font-size:14px;white-space:normal;widows:1;line-height:22px;background-color:#FFFFFF;">
	<span style="box-sizing:border-box;margin:0px;padding:0px;font-family:Arial;color:#666666;letter-spacing:0px;font-size:12px;"> 1<span style="box-sizing:border-box;margin:0px;padding:0px;font-family:宋体;">、通过</span></span><span style="box-sizing:border-box;margin:0px;padding:0px;letter-spacing:0px;color:#666666;font-family:宋体;font-size:12px;">柒付</span><span style="box-sizing:border-box;margin:0px;padding:0px;font-family:Arial;color:#666666;letter-spacing:0px;font-size:12px;">及其关联公司提供的</span><span style="box-sizing:border-box;margin:0px;padding:0px;letter-spacing:0px;color:#666666;font-family:宋体;font-size:12px;">柒付</span><span style="box-sizing:border-box;margin:0px;padding:0px;font-family:Arial;color:#666666;letter-spacing:0px;font-size:12px;">服务和其它服务，您可在</span><span style="box-sizing:border-box;margin:0px;padding:0px;letter-spacing:0px;color:#666666;font-family:宋体;font-size:12px;">柒付</span><span style="box-sizing:border-box;margin:0px;padding:0px;font-family:Arial;color:#666666;letter-spacing:0px;font-size:12px;">上查询交易</span><span style="box-sizing:border-box;margin:0px;padding:0px;font-family:宋体;color:#666666;letter-spacing:0px;font-size:12px;">信息和订单</span><span style="box-sizing:border-box;margin:0px;padding:0px;font-family:Arial;color:#666666;letter-spacing:0px;font-size:12px;">，</span><span style="box-sizing:border-box;margin:0px;padding:0px;font-family:宋体;color:#666666;letter-spacing:0px;font-size:12px;">并向指定商户付款购买商品</span><span style="box-sizing:border-box;margin:0px;padding:0px;font-family:Arial;color:#666666;letter-spacing:0px;font-size:12px;">。</span>
</p>
<p style="box-sizing:border-box;margin-top:0px;margin-bottom:0px;padding:0px;color:#333333;font-family:&quot;font-size:14px;white-space:normal;widows:1;line-height:22px;background-color:#FFFFFF;">
	<span style="box-sizing:border-box;margin:0px;padding:0px;font-family:Arial;color:#666666;letter-spacing:0px;font-weight:bold;font-size:12px;">2<span style="box-sizing:border-box;margin:0px;padding:0px;font-family:宋体;">、您在</span></span><span style="box-sizing:border-box;margin:0px;padding:0px;letter-spacing:0px;font-weight:bold;color:#666666;font-family:宋体;font-size:12px;">柒付</span><span style="box-sizing:border-box;margin:0px;padding:0px;font-family:Arial;color:#666666;letter-spacing:0px;font-weight:bold;font-size:12px;">交易过程中与商户会员发生交易纠纷时，一旦您或商户会员任一方或双方共同提交</span><span style="box-sizing:border-box;margin:0px;padding:0px;letter-spacing:0px;font-weight:bold;color:#666666;font-family:宋体;font-size:12px;">柒付</span><span style="box-sizing:border-box;margin:0px;padding:0px;font-family:Arial;color:#666666;letter-spacing:0px;font-weight:bold;font-size:12px;">要求调处，则</span><span style="box-sizing:border-box;margin:0px;padding:0px;letter-spacing:0px;font-weight:bold;color:#666666;font-family:宋体;font-size:12px;">柒付</span><span style="box-sizing:border-box;margin:0px;padding:0px;font-family:Arial;color:#666666;letter-spacing:0px;font-weight:bold;font-size:12px;">有权根据独立判断做出调处决定，您了解并同意接受</span><span style="box-sizing:border-box;margin:0px;padding:0px;letter-spacing:0px;font-weight:bold;color:#666666;font-family:宋体;font-size:12px;">柒付</span><span style="box-sizing:border-box;margin:0px;padding:0px;font-family:Arial;color:#666666;letter-spacing:0px;font-weight:bold;font-size:12px;">的判断和调处决定。该决定将对您具有约束力。</span>
</p>
<p style="box-sizing:border-box;margin-top:0px;margin-bottom:0px;padding:0px;color:#333333;font-family:&quot;font-size:14px;white-space:normal;widows:1;line-height:22px;background-color:#FFFFFF;">
	<span style="box-sizing:border-box;margin:0px;padding:0px;font-family:Arial;color:#666666;letter-spacing:0px;font-size:12px;"> 3<span style="box-sizing:border-box;margin:0px;padding:0px;font-family:宋体;">、您了解并同意，</span></span><span style="box-sizing:border-box;margin:0px;padding:0px;letter-spacing:0px;color:#666666;font-family:宋体;font-size:12px;">柒付</span><span style="box-sizing:border-box;margin:0px;padding:0px;font-family:Arial;color:#666666;letter-spacing:0px;font-size:12px;">有权应政府部门(<span style="box-sizing:border-box;margin:0px;padding:0px;font-family:宋体;">包括司法机关、公安机关、行政部门</span>)<span style="box-sizing:border-box;margin:0px;padding:0px;font-family:宋体;">的要求，向其提供您在</span></span><span style="box-sizing:border-box;margin:0px;padding:0px;font-family:宋体;color:#666666;letter-spacing:0px;font-size:12px;">柒付下</span><span style="box-sizing:border-box;margin:0px;padding:0px;font-family:Arial;color:#666666;letter-spacing:0px;font-size:12px;">交易记录等必要信息。</span><span style="box-sizing:border-box;margin:0px;padding:0px;font-family:Arial;color:#666666;letter-spacing:0px;font-weight:bold;font-size:12px;">如您有涉嫌侵犯他人知识产权、违法、盗刷别人银行卡等行为但不限于以上行为者，柒付亦有权在初步判断涉嫌侵权行为存在的情况下，向权利人提供您必要的交易信息和身份信息。</span>
</p>
<p style="box-sizing:border-box;margin-top:0px;margin-bottom:0px;padding:0px;color:#333333;font-family:&quot;font-size:14px;white-space:normal;widows:1;line-height:22px;background-color:#FFFFFF;">
	<span style="box-sizing:border-box;margin:0px;padding:0px;font-family:Arial;color:#666666;letter-spacing:0px;font-weight:bold;font-size:12px;">四、&nbsp;</span><span style="box-sizing:border-box;margin:0px;padding:0px;letter-spacing:0px;font-weight:bold;color:#666666;font-family:宋体;font-size:12px;">柒付</span><span style="box-sizing:border-box;margin:0px;padding:0px;font-family:Arial;color:#666666;letter-spacing:0px;font-weight:bold;font-size:12px;">使用规范</span>
</p>
<p style="box-sizing:border-box;margin-top:0px;margin-bottom:0px;padding:0px;color:#333333;font-family:&quot;font-size:14px;white-space:normal;widows:1;line-height:22px;background-color:#FFFFFF;">
	<span style="box-sizing:border-box;margin:0px;padding:0px;font-family:Arial;color:#666666;letter-spacing:0px;font-size:12px;"> 1<span style="box-sizing:border-box;margin:0px;padding:0px;font-family:宋体;">、使用</span></span><span style="box-sizing:border-box;margin:0px;padding:0px;letter-spacing:0px;color:#666666;font-family:宋体;font-size:12px;">柒付</span><span style="box-sizing:border-box;margin:0px;padding:0px;font-family:Arial;color:#666666;letter-spacing:0px;font-size:12px;">过程中，您承诺遵守以下约定：</span>
</p>
<p style="box-sizing:border-box;margin-top:0px;margin-bottom:0px;padding:0px;color:#333333;font-family:&quot;font-size:14px;white-space:normal;widows:1;line-height:22px;background-color:#FFFFFF;">
	<span style="box-sizing:border-box;margin:0px;padding:0px;font-family:Arial;color:#666666;letter-spacing:0px;font-size:12px;"> (1)<span style="box-sizing:border-box;margin:0px;padding:0px;font-family:宋体;">在使用</span></span><span style="box-sizing:border-box;margin:0px;padding:0px;letter-spacing:0px;color:#666666;font-family:宋体;font-size:12px;">柒付</span><span style="box-sizing:border-box;margin:0px;padding:0px;font-family:Arial;color:#666666;letter-spacing:0px;font-size:12px;">过程中实施的所有行为均遵守国家法律、法规等规范性文件及</span><span style="box-sizing:border-box;margin:0px;padding:0px;font-family:宋体;color:#666666;letter-spacing:0px;font-size:12px;">柒付</span><span style="box-sizing:border-box;margin:0px;padding:0px;font-family:Arial;color:#666666;letter-spacing:0px;font-size:12px;">各项规则的规定和要求，不违背社会公共利益或公共道德，不损害他人的合法权益，不违反本协议及相关规则。您如果违反前述承诺，产生任何法律后果的，您应以自己的名义独立承担所有的法律责任，并确保</span><span style="box-sizing:border-box;margin:0px;padding:0px;letter-spacing:0px;color:#666666;font-family:宋体;font-size:12px;">柒付</span><span style="box-sizing:border-box;margin:0px;padding:0px;font-family:Arial;color:#666666;letter-spacing:0px;font-size:12px;">免于因此产生任何损失。</span>
</p>
<p style="box-sizing:border-box;margin-top:0px;margin-bottom:0px;padding:0px;color:#333333;font-family:&quot;font-size:14px;white-space:normal;widows:1;line-height:22px;background-color:#FFFFFF;">
	<span style="box-sizing:border-box;margin:0px;padding:0px;font-family:Arial;color:#666666;letter-spacing:0px;font-size:12px;"> (2)<span style="box-sizing:border-box;margin:0px;padding:0px;font-family:宋体;">尊重并遵守行柒付平台的平台</span>规则、交易规则及相关声明，包括但不限于消费者保障规则、隐私条款、版权声明等一切现有的及将有的网站规则、交易规则及网站声明等。您知悉并接受上述规则的变更及公告生效方式，无需单独通知您。</span>
</p>
<p style="box-sizing:border-box;margin-top:0px;margin-bottom:0px;padding:0px;color:#333333;font-family:&quot;font-size:14px;white-space:normal;widows:1;line-height:22px;background-color:#FFFFFF;">
	<span style="box-sizing:border-box;margin:0px;padding:0px;font-family:Arial;color:#666666;letter-spacing:0px;font-size:12px;"> (3)<span style="box-sizing:border-box;margin:0px;padding:0px;font-family:宋体;">在与商户交易过程中，遵守诚实信用原则，不扰乱网上交易的正常秩序，不从事与网上交易无关的行为。</span></span>
</p>
<p style="box-sizing:border-box;margin-top:0px;margin-bottom:0px;padding:0px;color:#333333;font-family:&quot;font-size:14px;white-space:normal;widows:1;line-height:22px;background-color:#FFFFFF;">
	<span style="box-sizing:border-box;margin:0px;padding:0px;font-family:Arial;color:#666666;letter-spacing:0px;font-size:12px;"> (</span><span style="box-sizing:border-box;margin:0px;padding:0px;font-family:宋体;color:#666666;letter-spacing:0px;font-size:12px;">4</span><span style="box-sizing:border-box;margin:0px;padding:0px;font-family:Arial;color:#666666;letter-spacing:0px;font-size:12px;">)不对</span><span style="box-sizing:border-box;margin:0px;padding:0px;letter-spacing:0px;color:#666666;font-family:宋体;font-size:12px;">柒付</span><span style="box-sizing:border-box;margin:0px;padding:0px;font-family:Arial;color:#666666;letter-spacing:0px;font-size:12px;">上的任何数据作商业性利用，包括但不限于在未经</span><span style="box-sizing:border-box;margin:0px;padding:0px;letter-spacing:0px;color:#666666;font-family:宋体;font-size:12px;">柒付</span><span style="box-sizing:border-box;margin:0px;padding:0px;font-family:Arial;color:#666666;letter-spacing:0px;font-size:12px;">事先书面同意的情况下，以复制、传播等任何方式使用</span><span style="box-sizing:border-box;margin:0px;padding:0px;letter-spacing:0px;color:#666666;font-family:宋体;font-size:12px;">柒付</span><span style="box-sizing:border-box;margin:0px;padding:0px;font-family:Arial;color:#666666;letter-spacing:0px;font-size:12px;">上展示的资料。</span>
</p>
<p style="box-sizing:border-box;margin-top:0px;margin-bottom:0px;padding:0px;color:#333333;font-family:&quot;font-size:14px;white-space:normal;widows:1;text-indent:24px;line-height:22px;background-color:#FFFFFF;">
	<span style="box-sizing:border-box;margin:0px;padding:0px;font-family:Arial;color:#666666;letter-spacing:0px;font-size:12px;">(</span><span style="box-sizing:border-box;margin:0px;padding:0px;font-family:宋体;color:#666666;letter-spacing:0px;font-size:12px;">5</span><span style="box-sizing:border-box;margin:0px;padding:0px;font-family:Arial;color:#666666;letter-spacing:0px;font-size:12px;">)<span style="box-sizing:border-box;margin:0px;padding:0px;font-family:宋体;">不使用任何装置、软件或例行程序等技术手段干预或试图干预</span></span><span style="box-sizing:border-box;margin:0px;padding:0px;letter-spacing:0px;color:#666666;font-family:宋体;font-size:12px;">柒付</span><span style="box-sizing:border-box;margin:0px;padding:0px;font-family:Arial;color:#666666;letter-spacing:0px;font-size:12px;">的正常运作或正在</span><span style="box-sizing:border-box;margin:0px;padding:0px;font-family:宋体;color:#666666;letter-spacing:0px;font-size:12px;">柒付</span><span style="box-sizing:border-box;margin:0px;padding:0px;font-family:Arial;color:#666666;letter-spacing:0px;font-size:12px;">上进行的任何交易、活动。您不得采取任何将导致不合理的庞大数据负载加诸</span><span style="box-sizing:border-box;margin:0px;padding:0px;letter-spacing:0px;color:#666666;font-family:宋体;font-size:12px;">柒付</span><span style="box-sizing:border-box;margin:0px;padding:0px;font-family:Arial;color:#666666;letter-spacing:0px;font-size:12px;">网络设备的行动。</span>
</p>
<p style="box-sizing:border-box;margin-top:0px;margin-bottom:0px;padding:0px;color:#333333;font-family:&quot;font-size:14px;white-space:normal;widows:1;line-height:22px;background-color:#FFFFFF;">
	<br />
</p>
<p style="box-sizing:border-box;margin-top:0px;margin-bottom:0px;padding:0px;color:#333333;font-family:&quot;font-size:14px;white-space:normal;widows:1;line-height:22px;background-color:#FFFFFF;">
	<span style="box-sizing:border-box;margin:0px;padding:0px;font-family:宋体;color:#666666;letter-spacing:0px;font-weight:bold;font-size:12px;">五</span><span style="box-sizing:border-box;margin:0px;padding:0px;font-family:Arial;color:#666666;letter-spacing:0px;font-weight:bold;font-size:12px;">、</span><span style="box-sizing:border-box;margin:0px;padding:0px;font-family:宋体;color:#666666;letter-spacing:0px;font-weight:bold;font-size:12px;">纠纷处理</span>
</p>
<p style="box-sizing:border-box;margin-top:0px;margin-bottom:0px;padding:0px;color:#333333;font-family:&quot;font-size:14px;white-space:normal;widows:1;text-indent:24px;line-height:22px;background-color:#FFFFFF;">
	<span style="box-sizing:border-box;margin:0px;padding:0px;font-family:宋体;color:#666666;letter-spacing:0px;font-size:12px;">若交易过程中发生纠纷消费者需联系商户协商。若协商未果，请于交易当天联系柒付介入，我司将保证你的交易安全。</span>
</p>
<p style="box-sizing:border-box;margin-top:0px;margin-bottom:0px;padding:0px;color:#333333;font-family:&quot;font-size:14px;white-space:normal;widows:1;text-indent:24px;line-height:22px;background-color:#FFFFFF;">
	<span style="box-sizing:border-box;margin:0px;padding:0px;font-family:宋体;color:#666666;letter-spacing:0px;font-size:12px;">如超过两天担保，我司将介入，消费者与商户进行协调并举证。如在此期间并未圆满解决，消费者或商户可向公安机关报案，柒付将积极协助公安机关处理。</span>
</p>
<p style="box-sizing:border-box;margin-top:0px;margin-bottom:0px;padding:0px;color:#333333;font-family:&quot;font-size:14px;white-space:normal;widows:1;text-indent:24px;line-height:22px;background-color:#FFFFFF;">
	<span style="box-sizing:border-box;margin:0px;padding:0px;font-family:宋体;color:#666666;letter-spacing:0px;font-size:12px;"><br style="box-sizing:border-box;" />
</span>
</p>
<p style="box-sizing:border-box;margin-top:0px;margin-bottom:0px;padding:0px;color:#333333;font-family:&quot;font-size:14px;line-height:20px;white-space:normal;widows:1;background-color:#FFFFFF;">
	<span style="box-sizing:border-box;margin:0px;padding:0px;color:#FF0000;">在法律允许的最大范围内，柒付保留对本协议条款的最终解释权。</span>
</p>
<p style="box-sizing:border-box;margin-top:0px;margin-bottom:0px;padding:0px;color:#333333;font-family:&quot;font-size:14px;line-height:20px;white-space:normal;widows:1;background-color:#FFFFFF;">
	<span style="box-sizing:border-box;margin:0px;padding:0px;color:#FF0000;">如您对本条款内容有任何疑问，可联系官方客服人员进行解答。</span>
</p>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <?php require_once 'footer.php' ?>